start python .\terminal.py 10
start python .\terminal.py 11
start python .\terminal.py 12
start python .\terminal.py 13
start python .\terminal.py 14
start python .\terminal.py 15
start python .\terminal.py 16
start python .\terminal.py 17
start python .\terminal.py 18
start python .\terminal.py 19
start python .\terminal.py 21
start python .\terminal.py 22
start python .\terminal.py 23
start python .\terminal.py 24
start python .\terminal.py 25
start python .\terminal.py 26